# Generated by Django 3.1.6 on 2021-05-03 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('longlatitude', models.CharField(blank=True, max_length=200, null=True, verbose_name='编号')),
                ('longtitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='纬度')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('type', models.CharField(default='自助餐', max_length=32, verbose_name='类型')),
                ('position', models.CharField(blank=True, max_length=32, null=True, verbose_name='商区')),
                ('rate_taste', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='口味')),
                ('rate_surround', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='环境')),
                ('rate_service', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='服务')),
                ('res_image', models.ImageField(blank=True, null=True, upload_to='resturants/', verbose_name='图片')),
            ],
            options={
                'verbose_name': '餐厅',
                'verbose_name_plural': '餐厅',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='账号')),
                ('password', models.CharField(default='123456', max_length=32, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号码')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_time', models.DateTimeField(auto_now_add=True, verbose_name='就餐时间')),
                ('resturant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resturants.resturant', verbose_name='餐厅id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resturants.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '就餐信息',
                'verbose_name_plural': '就餐信息',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_taste', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='口味')),
                ('rate_surround', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='环境')),
                ('rate_service', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='服务')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('content', models.CharField(default='用户暂未留下评价内容', max_length=255, verbose_name='评论内容')),
                ('resturant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resturants.resturant', verbose_name='餐厅id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resturants.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
