# Generated by Django 3.1.6 on 2021-03-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='longlatitude',
            field=models.CharField(max_length=200, verbose_name='坐标'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456', max_length=32, verbose_name='密码'),
        ),
    ]
