# Generated by Django 3.1.6 on 2021-03-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0003_auto_20210317_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
    ]
