# Generated by Django 3.1.6 on 2021-03-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0004_auto_20210317_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='longlatitude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='坐标'),
        ),
        migrations.AlterField(
            model_name='resturant',
            name='position',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='商区'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
