# Generated by Django 3.1.6 on 2021-03-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0005_auto_20210318_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号码'),
        ),
    ]
