# Generated by Django 3.1.6 on 2021-03-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0006_auto_20210318_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='mark',
        ),
        migrations.AddField(
            model_name='info',
            name='rate_service',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='服务'),
        ),
        migrations.AddField(
            model_name='info',
            name='rate_surround',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='环境'),
        ),
        migrations.AddField(
            model_name='info',
            name='rate_taste',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='口味'),
        ),
    ]
