# Generated by Django 3.1.6 on 2021-03-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0008_auto_20210318_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, verbose_name='账号'),
        ),
    ]
